language: c
sudo: required
install: test -e .travis-ocaml.sh || wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-ocaml.sh
script: bash -ex .travis-ocaml.sh
env:
  - OCAML_VERSION=4.05
os:
  - linux
