name: LSIF
on: [push, pull_request]
jobs:
  build:
    name: Build and push LSIF data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: OCaml setup
        uses: avsm/setup-ocaml@master
        with:
          ocaml-version: '4.08.1'
      - run: opam pin add comby.dev -n .
      - run: opam depext -yt comby
      - run: opam install -t . --deps-only
      - run: opam pin add -y merlin-lsif https://github.com/rvantonder/merlin.git\#lsif
      - run: opam pin add -y lsif-ocaml https://github.com/rvantonder/lsif-ocaml.git
      - run: opam exec -- dune build
#     - name: Setup tmate session
#       uses: mxschmitt/action-tmate@v1
      - run: opam exec -- lsif-ocaml-dump
#     - run: opam exec -- lsif-ocaml -only-type-hovers > dump.lsif
      - run: opam exec -- lsif-ocaml > dump.lsif
      - name: Upload LSIF data
        uses: sourcegraph/lsif-upload-action@master
        continue-on-error: true
        with:
          endpoint: https://sourcegraph.com
          github_token: ${{ secrets.GITHUB_TOKEN }}
          file: dump.lsif
